# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose
# values do not exceed four million, find the sum of the
# even-valued terms.
require 'pry'

fibonacci_sequence = [1]
previous_term = 0
current_term = 1
next_term = previous_term + current_term

while fibonacci_sequence[-1] <= 4000000 do
  fibonacci_sequence << next_term
  next_term = previous_term + current_term
  previous_term = current_term
  current_term = next_term
end

fibonacci_sequence.delete_at(-1)

sum = fibonacci_sequence.find_all { |int| int.even? }.sum

puts sum
